import React from 'react';

// Simple Styles
export const styles: Record<string, React.CSSProperties> = {
    overlay: {
        position: 'fixed' as const,
        top: 0,
        right: 0,
        width: '320px',
        height: '100vh',
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        color: '#eee',
        padding: '20px', 
        boxSizing: 'border-box',
        overflowY: 'auto', 
        zIndex: 10000,
        fontFamily: "'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
        backdropFilter: 'blur(4px)',
        borderLeft: '1px solid #333',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottom: '1px solid #444',
        marginBottom: '20px',
        paddingBottom: '10px',
    },
    content: {
        flex: 1,
        overflowY: 'auto',
        padding: '20px',
    },
    titleGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    pauseBtn: {
        background: 'none',
        border: '1px solid #444',
        borderRadius: '4px',
        padding: '6px 12px',
        fontSize: '13px',
        cursor: 'pointer',
        fontWeight: 'bold',
        textTransform: 'uppercase',
        marginTop: '4px',
    },
    closeBtn: {
        background: 'none',
        border: 'none',
        color: '#888',
        fontSize: '24px',
        cursor: 'pointer',
    },
    section: {
        marginBottom: '24px',
    },
    sectionTitle: {
        fontSize: '14px',
        textTransform: 'uppercase',
        letterSpacing: '1px',
        color: '#888',
        borderBottom: '1px solid #333',
        paddingBottom: '4px',
        marginBottom: '12px',
    },
    button: {
        display: 'block',
        width: '100%',
        padding: '8px 12px',
        marginBottom: '8px',
        borderRadius: '4px',
        cursor: 'pointer',
        fontWeight: 'bold',
        fontSize: '13px',
        transition: 'all 0.2s',
        textAlign: 'center',
    },

    hint: {
        fontSize: '11px',
        color: '#666',
        marginBottom: '10px',
        fontStyle: 'italic',
    },
    activeRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '8px',
        backgroundColor: '#333',
        marginBottom: '4px',
        borderRadius: '4px',
        fontSize: '12px',
    },
    removeBtn: {
        background: 'none',
        border: 'none',
        color: '#ff6b6b',
        cursor: 'pointer',
        fontWeight: 'bold',
        padding: '0 4px',
    },
    searchInput: {
        width: '100%',
        padding: '8px',
        marginBottom: '10px',
        backgroundColor: '#222',
        border: '1px solid #444',
        borderRadius: '4px',
        color: '#eee',
        fontSize: '13px',
    },
    scrollList: {
        // maxHeight: '300px', // Removed to show all items
        overflowY: 'visible',
        paddingRight: '4px',
    },
    footer: {
        marginTop: '30px',
        paddingTop: '20px',
        paddingBottom: '40px',
        display: 'flex',
        justifyContent: 'center',
        borderTop: '1px solid #333',
    },
    scrollTopBtn: {
        backgroundColor: '#333',
        color: '#fff',
        border: '1px solid #555',
        borderRadius: '20px',
        padding: '8px 24px',
        cursor: 'pointer',
        fontSize: '12px',
        fontWeight: 'bold',
        textTransform: 'uppercase',
        transition: 'all 0.2s',
        outline: 'none',
    },
    levelControls: {
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        marginRight: '8px',
        backgroundColor: '#222',
        borderRadius: '12px',
        padding: '2px 4px',
    },
    levelBtn: {
        background: 'none',
        border: 'none',
        color: '#888',
        cursor: 'pointer',
        fontSize: '14px',
        fontWeight: 'bold',
        padding: '0 4px',
        width: '20px',
        textAlign: 'center',
    },
    levelDisplay: {
        fontSize: '11px',
        color: '#ccc',
        minWidth: '35px',
        textAlign: 'center',
        fontWeight: 'bold',
    },

};
